name: Linux Build
on:
  push:
    branches:
    - nds
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install DevkitPro Pacman
      run: |
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x ./install-devkitpro-pacman
        sudo ./install-devkitpro-pacman
        sudo dkp-pacman nds-dev
        
    - name: Install Tools
      run: |
        sudo apt-get update
        sudo apt install -y build-essential git python sox
    - name: Compile
      run: |
       make -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: sm64
        path: |
          ./build/us_nds/*.nds
