name: Docker Build
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.wiiogc -j$(nproc)
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: sm64
        path: |
          ./*.nds
